name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - "assets/**"
      - "infrastructure/**"
      - "*.md"

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::109260931664:role/github-actions-role
      #     aws-region: eu-west-1
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o out .
          zip -9 -j deploy.zip out
      # - name: Deploy
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name $FUNCTION_NAME \
      #       --zip-file deploy.zip \
      #       --publish
